"""empty message

Revision ID: b4203f1ccf97
Revises: None
Create Date: 2016-02-10 02:49:09.636855

"""

# revision identifiers, used by Alembic.
revision = 'b4203f1ccf97'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_block', sa.Column('contents', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'content_block', ['name'])
    op.drop_column('content_block', 'value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_block', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'content_block', type_='unique')
    op.drop_column('content_block', 'contents')
    ### end Alembic commands ###
